/*
 * Album Store API
 *
 * CS6650 Fall 2023
 *
 * API version: 1.0.0
 * Contact: i.gorton@northeasern.edu
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"encoding/json"
	"net/http"
	"strings"
)

func GetAlbumByKey(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	urlString := r.URL.String()

	if urlString == "" {
		http.Error(w, "missing parameters", http.StatusNotFound)
		return
	}
	urlSplit := strings.Split(urlString, "/")
	albumId := urlSplit[3]
	if albumId != "" {
		responseJSON, jsonErr := json.Marshal(albums[0])

		if jsonErr != nil {
			http.Error(w, "Server HTTP 500 Json Error", http.StatusInternalServerError)
			return
		}

		w.WriteHeader(http.StatusOK)
		w.Write(responseJSON)

		//_, writeErr := w.Write(responseJSON)
		//if writeErr != nil {
		//	http.Error(w, "HTTP 500 serverError", http.StatusInternalServerError)
		//	return
		//}
	}
	w.WriteHeader(http.StatusOK)
}

func NewAlbum(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
